{
 "title": "Database Exporter Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "query": {
     "query": "label_values(pg_stat_database_xact_commit, datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions succes rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  100 * increase(pg_transactions_commits{database_name=~\"$database\"}[1h])\r\n      / (increase(pg_transactions_commits{database_name=~\"$database\"}[1h]) + increase(pg_transactions_rollbacks{database_name=~\"$database\"}[1h]))\r\n) \r\nby (database_name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Rolled Back/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=~\"$database\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pg_roles_list_dummy_value\r\n", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Database Size (GB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((pg_database_size_bytes{datname=~\"$database\"}) / 1024 / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Rows per Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_all_db_tables_estimated_rows{database_name=~\"$database\"}\r\n",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$database\", state=\"active\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp File Usage (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_bytes{datname=~\"$database\"}[5m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (hours) ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - pg_postmaster_start_time_seconds) / 3600\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{datname=~\"$database\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions Committed/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=~\"$database\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}